### ISSUE TITLE
Error when adding a new row in the grid

### ISSUE THREAD

**Issue by dandv** [webix-hub/webix-meteor-example#4]
Navigate to the grid, navigate back, then once again to the grid. Add a row.

![meteor example error](https://cloud.githubusercontent.com/assets/33569/7341958/9e5b98a8-ec60-11e4-9da1-8ac22b04363a.gif)

```
Exception in queued task: TypeError: Cannot read property 'length' of null
    at Object.webix.DataStore.add (http://cdn.webix.io/2.2/webix.js:356:68)
    at Object.add (http://cdn.webix.io/2.2/webix.js:363:346)
    at Object.<anonymous> (http://dandascalescu.com:3000/webix-meteor.js:49:11)
    at Object.webix.DataProcessor.webix.proto.ignore (http://cdn.webix.io/2.2/webix.js:1043:51)
    at Object.cursor.observe.added (http://dandascalescu.com:3000/webix-meteor.js:48:20)
    at LocalCollection._observeFromObserveChanges.observeChangesCallbacks.added (http://dandascalescu.com:3000/packages/minimongo.js?e8806aa7782b729b2517ebc0cd10b321667f1427:3897:28)
    at Object.LocalCollection._CachingChangeObserver.self.applyChange.added (http://dandascalescu.com:3000/packages/minimongo.js?e8806aa7782b729b2517ebc0cd10b321667f1427:3797:44)
    at http://dandascalescu.com:3000/packages/minimongo.js?e8806aa7782b729b2517ebc0cd10b321667f1427:421:13
    at _.extend.runTask (http://dandascalescu.com:3000/packages/meteor.js?81e2f06cff198adaa81b3bc09fc4f3728b7370ec:692:11)
    at _.extend.flush (http://dandascalescu.com:3000/packages/meteor.js?81e2f06cff198adaa81b3bc09fc4f3728b7370ec:720:10)
webix-meteor.js:109 t8tCwSMJ2k459PZ2z
```

**Comment by xcrypto** [comment]
hi Dan, 

I've been experimenting a bit with your Meteor / Webix package... I am also getting this error... 

Have you determined the root cause of this error?  

I navigate to the view and the table displays properly; however, when I navigate away to any other view, I get the following:  

Exception in queued task: TypeError: Cannot read property 'name' of undefined
    at Object.webix.DataProcessor.webix.proto.master_setter (http://localhost:3000/packages/webix_webix.js?e128e5cf11363acc0a25178c1bf2fd39560b985d:27216:12)
    at Object.webix.Settings._define (http://localhost:3000/packages/webix_webix.js?e128e5cf11363acc0a25178c1bf2fd39560b985d:2109:50)
    at Object.webix.Settings._parseSeetingColl (http://localhost:3000/packages/webix_webix.js?e128e5cf11363acc0a25178c1bf2fd39560b985d:2115:10)
    at Object.webix.Settings._parseSettings (http://localhost:3000/packages/webix_webix.js?
...
...

I've tried to debug it - no luck, so far... 

JC
